#!/bin/bash

clear
echo "=============================================
------ MISE À JOUR COMPLETE SU SYSTEME ------
============================================="
sleep 3
apt update && apt upgrade -y
clear

echo "======================================
------ INSTALLATION DES PAQUETS ------
======================================"
sleep 3
apt install ssh zip nmap locate ncdu curl git screen dnsutils net-tools sudo lynx tree -y
clear

echo "=========================================
------ INSTALLATION COUCHE NETBIOS ------
========================================="
sleep 3
apt install winbind samba -y
cp /etc/nsswitch.conf /etc/nsswitch_backup.conf
echo "
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# info libc 'Name Service Switch' for information about this file.

passwd:         files systemd winbind
group:          files systemd winbind
shadow:         files systemd
gshadow:        files systemd

hosts:          files dns wins
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis" > /etc/nsswitch.conf

echo "export LS_OPTIONS='--color=auto'
eval \"\$(dircolors)\"
alias ls='ls \$LS_OPTIONS'
alias ll='ls \$LS_OPTIONS -l'
alias l='ls \$LS_OPTIONS -lA'" >> /root/.bashrc
clear

echo "=================================
------ INSTALLATION WEBMIN ------
================================="
sleep 3
curl -o webmin-setup-repo.sh https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repo.sh
sh webmin-setup-repo.sh --force
apt install webmin -y --install-recommends
rm post-install.sh
clear


echo "========================================
------ INSTALLATION DE GAMESHELL -------
========================================"
sleep 3
apt install bsdgames -y
clear

echo "=====================================================================
---------- Post-install TERMINÉ, la machine va rédemarrée -----------
------ WEBMIN accessible via : https://IP_DE_LA_MACHINE:10000 -------
--------------- Retrouvez GAMESHELL dans : /usr/games ---------------
====================================================================="
sleep 10
systemctl reboot
