#!/bin/bash

set -e
echo ------! MISE À JOUR COMPLETE SU SYSTEME !------
apt update && apt upgrade -y

echo ------! INSTALLATION DES PAQUETS !------
apt install ssh -y
apt install zip -y
apt install nmap -y
apt install locate -y
apt install ncdu -y
apt install curl -y
apt install git -y
apt install screen -y
apt install dnsutils -y
apt install net-tools -y
apt install sudo -y
apt install lynx -y

echo ------! INSTALLATION COUCHE NETBIOS !------

apt install winbind samba -y
if ! grep -q "^hosts:.*wins" /etc/nsswitch.conf; then
    sed -i 's/^\(hosts:.*\)dns/\1dns wins/' /etc/nsswitch.conf || \
        echo "hosts: files dns wins" >> /etc/nsswitch.conf
else
    echo "→ Ligne WINS déjà présente"
fi
echo "export LS_OPTIONS='--color=auto'" >> /root/.bashrc
echo "eval \"\$(dircolors)\"" >> /root/.bashrc
echo "alias ls='ls \$LS_OPTIONS'" >> /root/.bashrc
echo "alias ll='ls \$LS_OPTIONS -l'" >> /root/.bashrc
echo "alias l='ls \$LS_OPTIONS -lA'" >> /root/.bashrc

echo ------! INSTALLATION WEBMIN !------

curl -o webmin-setup-repo.sh https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repo.sh
sh webmin-setup-repo.sh -y
apt install webmin --install-recommends -y

echo ------! POUR LE FUN !-------

apt install bsdgames -y

echo ------! FINI !-------
echo ---------------------
echo ---------------------
echo ---------------------
reboot
